### ISSUE TITLE
Have a nice Date

### ISSUE THREAD

**Issue by DTheRealK** [Holzkohlen/FileManagement#7]
Date Variablen

**Comment by dedChar** [comment]
Duplikat von #6 oder nich

**Comment by DTheRealK** [comment]
Komm null damit klar xD

**Comment by dedChar** [comment]
Ich merks xD

**Comment by DTheRealK** [comment]
<HR> <H2>HTML4TheWIN<H2> <HR>

**Comment by DTheRealK** [comment]
[MEME](http://s.quickmeme.com/img/75/7509f68823389e4af3777ca6d3744c632cc32ab3547bc56e319126aa29ab149a.jpg)
